server:
  port: 8080
  error:
    path: "/error"
  max-http-header-size: 10000000
  server-header:
  servlet:
    context-path:
  tomcat:
    max-http-form-post-size: 10000000

oidc:
  discovery_endpoint: "https://connect.dev.openconext.local/oidc/.well-known/openid-configuration"
  client_id: "oidc-playground.dev.openconext.local"
  secret: "secretsecret"
  jwt_secret: "very-long-long-long-long-long-secret"
  resource_server_id: "oidc-playgroundrs.dev.openconext.local"
  resource_server_secret: "secretsecret"
  redirect_uri: "https://oidc-playground.dev.openconext.local/redirect"
  redirect_uri_form_post: "https://oidc-playground.dev.openconext.local/oidc/api/redirect"
  client_redirect_uri: "https://connect.dev.openconext.local/redirect"

gui:
  disclaimer:
    background-color: red
    content: DEV
