logging:
  level:
    root: INFO
    org.springframework.session: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: INFO
    org.springframework.data: INFO

cron:
  node-cron-job-responsible: true
  expression: "0 0/15 * * * *"

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

mongodb_db: oidc_test
jwks_key_store_path: classpath:/oidc.keystore.jwks.json
secret_key_set_path: classpath:/secret_keyset.json
associated_data: 4CEFFA8B-90DD-4737-8B04-6DA51C5B29AE
private_key_path: classpath:/id_rsa
certificate_path: classpath:/id_rsa.pub

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
  thymeleaf:
    cache: false
  security:
    saml2:
      network:
        read-timeout: 10000
        connect-timeout: 5000
      service-provider:
        entity-id: https://org.openconext.oidc.ng
        prefix: oidc
        alias: oidc-proxy
        base-path: http://localhost:8080
        sign-metadata: true
        sign-requests: true
        want-assertions-signed: true
        single-logout-enabled: false
        name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
        providers:
          - alias: engine-test2
            metadata: https://engine.test.surfconext.nl/authentication/idp/metadata
            link-text: EngineBlock test2
            name-id: https://engine.test.surfconext.nl/authentication/idp/metadata
            assertion-consumer-service-index: 0

manage:
  user: manage
  password: secret

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
      show-details: when_authorized
