logging:
  level:
    root: INFO
    playground: DEBUG
    org.springframework: INFO

server:
  port : 8081
  max-http-header-size: 10000000
  tomcat:
    max-http-post-size: 10000000
  server-header:
  servlet:
    context-path: /oidc/api

oidc:
  discovery_endpoint: "https://oidcng.test2.surfconext.nl/oidc/.well-known/openid-configuration"
  # Use this when you want to test against a local instance of OIDC-NG
#  discovery_endpoint: "http://localhost:8080/oidc/.well-known/openid-configuration"
  client_id: "playground_client"
  secret: "secret"
  resource_server_id: "resource-server-playground-client"
  resource_server_secret: "secret"
  redirect_uri: "http://localhost:3000/redirect"
  redirect_uri_form_post: "http://localhost:3000/oidc/api/redirect"
  client_redirect_uri: "http://localhost:3000/redirect"

gui:
  disclaimer:
    background-color: red
    content: LOCAL

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
