logging:
  level:
    root: INFO
    playground: DEBUG
    org.springframework: INFO

server:
  port : 8079
  error:
    path: "/error"
  max-http-header-size: 10000000
  server-header:
  servlet:
    context-path: /oidc/api
  tomcat:
    max-http-form-post-size: 10000000

oidc:
  discovery_endpoint: "https://connect.test2.surfconext.nl/oidc/.well-known/openid-configuration"
  # Use this when you want to test against a local instance of OIDC-NG
#  discovery_endpoint: "http://localhost:8080/oidc/.well-known/openid-configuration"
  client_id: "playground_client"
  secret: "secret"
  jwt_secret: "very-long-long-long-long-long-secret"
  resource_server_id: "resource-server-playground-client"
  resource_server_secret: "l36VaA1YXR9gG7Pw9POuiQ60h1rU3IhfT5kC"
  redirect_uri: "http://localhost:3006/redirect"
  redirect_uri_form_post: "http://localhost:3006/oidc/api/redirect"
  client_redirect_uri: "http://localhost:3006/redirect"

gui:
  disclaimer:
    background-color: red
    content: LOCAL

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

acr:
  values:
    - "https://eduid.nl/trust/validate-names"
    - "https://eduid.nl/trust/linked-institution"
    - "https://eduid.nl/trust/affiliation-student"
    - "https://refeds.org/profile/mfa"
