version: 2
updates:
  - package-ecosystem: npm
    directory: "/oidc-playground-client"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
