language: java
jdk:
- oraclejdk8
dist: trusty
node_js:
- '10.14.2'

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.m2

matrix:
  fast_finish: true

before_install:
- pip install --user codecov
- nvm install 10.14.2
- npm install -g yarn
- yarn install

install:
- cd oidc-playground-client && yarn install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test
- cd oidc-playground-client && yarn install && CI=true yarn test && yarn build

after_success:
- codecov
