language: java
jdk:
- oraclejdk8
dist: trusty
node_js:
- '8'

env:
  - MONGODB=3.4.3

matrix:
  fast_finish: true

before_install:
- wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
- tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
- ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
- pip install --user codecov
- nvm install 8
- npm install -g yarn
- yarn install
install:
- cd oidc-playground-client && yarn install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
- ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
script:
- mvn test
- cd oidc-playground-client && yarn install && CI=true yarn test && yarn build
after_script:
- pkill mongod
after_success:
- codecov