# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v4
      with:
        node-version: '17'
    - run: export NODE_OPTIONS=--openssl-legacy-provider

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: 'maven'

    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: export NODE_OPTIONS=--openssl-legacy-provider && mvn -B clean install

    - name: Codecov
      uses: codecov/codecov-action@v1.3.1
